apiVersion: apps/v1
kind: Deployment
metadata:
  name: track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: track
  template:
    metadata:
      labels:
        app: track
    spec:
      containers:
        - name: track
          image: dimleo/track
          ports:
            - containerPort: 5000
      restartPolicy: Always
