apiVersion: v1
kind: Service
metadata:
  name: mongodb-track
  labels:
    app: mongodb-track
spec:
  clusterIP: None
  selector:
    app: mongodb-track
  ports:
    - port: 27017
      targetPort: 27017
