apiVersion: v1
kind: Service
metadata:
  name: playlist
  labels:
    app: playlist
spec:
  type: ClusterIP
  selector:
    app: playlist
  ports:
    - name: http
      port: 4000
      targetPort: 4000
