apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-playlist
spec:
  serviceName: "mongodb-playlist"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-playlist
  template:
    metadata:
      labels:
        app: mongodb-playlist
        selector: mongodb-playlist
    spec:
      containers:
        - name: mongodb-playlist
          image: mongo:4.0.17
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data-playlist
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data-playlist
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
