apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-track
spec:
  serviceName: "mongodb-track"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-track
  template:
    metadata:
      labels:
        app: mongodb-track
        selector: mongodb-track
    spec:
      containers:
        - name: mongodb-track
          image: mongo:4.0.17
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data-track
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data-track
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
