apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: piplib-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: gateway-credential
      hosts:
        - '*'
